name: TestDeploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER_NAME: ${{ secrets.EC2_USER_NAME }}
          HOST_NAME: ${{ secrets.EC2_HOST_NAME }}
          ACCESS_KEY: ${{ secrets.AWS_USER_ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_KEY }}
          SECURITY_GROUP: ${{ secrets.AWS_TARGET_SG }}
        run: |
          # https://github.com/haythem/public-ip
          IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`

          # AWS CLIをインストール
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          # AWS CLIに設定をする
          printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\nap-northeast-1\njson\n" | aws configure --profile eyemovic-dev
          aws configure get aws_access_key_id --profile eyemovic-dev

          # SSH接続して、git pullする
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          cd /home/ec2-user/vue-articles &&
          sudo git checkout main  &&
          sudo git pull origin main &&
          '

          # yarnでビルドを行い、nuxtを再反映
          yarn upgrade
          yarn build
          pm2 restart vue-articles

          
